---
 - name:  apply configuration to informatica servers
   hosts: all
   gather_facts: yes
   become: True
   become_method: sudo
   become_user: root
   remote_user: ansible
   vars:
     ansible_ssh_private_key_file: /var/lib/awx/.ssh/ansible.pem

   roles:
#     - common
#     - GrpAdd
#     - UserAdd
#     - Sudoers
#     - MkDir
#     - ChgPerms
#     - CpFiles
#     - FetchFiles
#     - CmdRoot
#     - CmdUser
     - CmdOS
#     - ReachableHosts
#     - SWInstall
#     - SrvEnable
#     - UserDel
#     - GrpDel
#     - test 
