---
 - name:  apply configuration
   hosts: all
   gather_facts: yes
   become: True
   become_method: sudo
   become_user: root
   remote_user: ansible
   vars:
     ansible_ssh_private_key_file: /home/dmoody/.ssh/id_ed25519 

   roles:
#     - common
#     - GrpAdd
#     - UserAdd
#     - Sudoers
#     - MkDir
#     - ChgPerms
     - CpFiles
#     - FetchFiles
#     - CmdRoot
#     - CmdUser
#     - CmdOS
#     - ReachableHosts
#     - SWInstall
#     - SrvEnable
#     - UserDel
#     - GrpDel
#     - test 
