---
# tasks file for ChgPerms

 - include_vars:
     dir: /var/lib/awx/projects/_23__dr1_ansible_dev/group_vars
     files_matching: ChgPerms.yml

 - name: Recursively change ownership of a directory
   file:
     path: "{{ item.path }}"
     state: "{{ item.state }}"
     recurse: "{{ item.recurse }}"
     owner: "{{ item.owner }}"
     group: "{{ item.group }}"
     mode: "{{ item.mode }}"
   with_items: "{{ files }}"
